### ISSUE TITLE
Opened DMG has application misaligned.

### ISSUE THREAD

**Issue by hobleyd** [QQxiaoming/create-dmg-action#127]
![image](https://github.com/QQxiaoming/create-dmg-action/assets/25625171/e4b639c9-9ac7-482d-a5ff-1fa38c8f3d0f)

When I create my DMG and open it, the icon is misaligned. How would I fix that, please?

```
- uses: QQxiaoming/create-dmg-action@v0.0.2
       with:
         name: 'shackleton'
         srcdir: 'build/macos/Build/Products/Release/shackleton.app'
```

(It's a Flutter app if that makes any difference. The image is in there, just way over to the right!

**Comment by fr3ak2402** [comment]
@hobleyd 

I have a question, I would also like to use this action.

Does this action automatically upload the DMG, so that you can then also Downloaden in the area of the action?

**Comment by hobleyd** [comment]
```
     - uses: QQxiaoming/create-dmg-action@v0.0.2
       with:
         name: 'shackleton'
         srcdir: 'build/macos/Build/Products/Release/shackleton.app'
     # Upload generated dmg to the artifacts.
     - uses: actions/upload-artifact@v1
       with:
         name: shackleton.dmg
         path: shackleton.dmg
```
